# Generated by Django 5.1.4 on 2024-12-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyu_app', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
    ]
