# Generated by Django 5.1.4 on 2024-12-23 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyu_app', '0003_remove_userprofileinfo_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
    ]
