# Generated by Django 5.1.4 on 2025-01-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyu_app', '0009_alter_progress_class_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='class_number',
            field=models.IntegerField(default=1),
        ),
    ]
